- README.md
DTSBPS-430
Adding code coverage badge
```
[ ] Yes
[X] No
```
> DTSBPS-430: adding code coverage badge

- build.gradle
DTSBPS-626
Fix spring-vulnerabilities
```
[ ] Yes
[x] No
```
> DTSBPS-626:  fix spring-vulnerabilities

- src/main/java/uk/gov/hmcts/reform/sendletter/blob/BlobProcessor.java
- src/main/java/uk/gov/hmcts/reform/sendletter/blob/component/BlobReader.java
- src/main/java/uk/gov/hmcts/reform/sendletter/blob/component/BlobUpload.java
- src/main/java/uk/gov/hmcts/reform/sendletter/config/AccessTokenProperties.java
- src/main/java/uk/gov/hmcts/reform/sendletter/exceptions/LeaseIdNotPresentException.java
- src/main/java/uk/gov/hmcts/reform/sendletter/exceptions/UnableToZipException.java
- src/main/java/uk/gov/hmcts/reform/sendletter/model/BlobInfo.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/sendletter/blob/BlobProcessorTest.java
- src/test/java/uk/gov/hmcts/reform/sendletter/blob/component/BlobReaderTest.java
- src/test/java/uk/gov/hmcts/reform/sendletter/blob/component/BlobUploadTest.java
https://tools.hmcts.net/jira/browse/DTSBPS-612
Zip process code optimization.
```
[ ] Yes
[x] No
```
> DTSBPS-612: Zip process code optimization.

- build.gradle
- config/owasp/suppressions.xml
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/sendletter/services/SasTokenGeneratorServiceTest.java
DTSBPS-633
spring boot upgrade
```
[ ] Yes
[x] No
```
> DTSBPS-633: spring boot upgrade

- charts/rpe-send-letter-service-container-proc/Chart.yaml
- charts/rpe-send-letter-service-container-proc/values.yaml
> Test more jobs running at once

- charts/rpe-send-letter-service-container-proc/Chart.yaml
- charts/rpe-send-letter-service-container-proc/values.yaml
adding blobPrefix
adding blobPrefix
```
[ ] Yes
[x] No
```
> adding blobPrefix

- charts/rpe-send-letter-service-container-proc/Chart.yaml
- charts/rpe-send-letter-service-container-proc/values.yaml
adding completions to 5
adding completions to 5
```
[ ] Yes
[x] No
```
> adding completions to 5

- src/main/java/uk/gov/hmcts/reform/sendletter/Application.java
DTSBPS 642
logging message
```
[ ] Yes
[ x] No
```
> DTSBPS 642 logging message

- src/main/java/uk/gov/hmcts/reform/sendletter/Application.java
DTSBPS-642
logging message in app-insight
```
[ ] Yes
[x] No
```
> DTSBPS-642: logging message in app-insight

- Jenkinsfile_CNP
DTSBPS-658
sync with master
```
[ ] Yes
[ x] No
```
> DTSBPS-658: sync with master

- build.gradle
na
downgrade nettey lib, 4.1.68 breaking the functionality
```
[ ] Yes
[x] No
```
>  downgrade nettey lib, 4.1.68 breaking the functionality

- src/main/java/uk/gov/hmcts/reform/sendletter/blob/component/BlobReader.java
na
avoid filling log
```
[ ] Yes
[x] No
```
> avoid filling with known traces

- build.gradle
- config/owasp/suppressions.xml
Dtsbps 773
resolve CVE
```
[ ] Yes
[ x] No
```
> Dtsbps 773 fix CVE

- build.gradle
- src/test/java/uk/gov/hmcts/reform/sendletter/services/SasTokenGeneratorServiceTest.java
na
bump azure blob storage lib
```
[ ] Yes
[x] No
```
> bump azure blob storage lib

- charts/rpe-send-letter-service-container-proc/Chart.yaml
- charts/rpe-send-letter-service-container-proc/values.perftest.template.yaml
> Increase parallelism and reduce polling interval

- config/owasp/suppressions.xml
Suppress vulnerabilities
```
[ ] Yes
[x] No
```
> Suppress vulnerabilities

- config/owasp/suppressions.xml
> Vulnerability suppress

- config/owasp/suppressions.xml
> DTSBPS-960: Fix CVE 2022 22976

- charts/rpe-send-letter-service-container-proc/Chart.yaml
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSBPS-997
```
[ ] Yes
[x] No
```
> Suppress CVE-2022-33915

- build.gradle
- charts/rpe-send-letter-service-container-proc/Chart.yaml
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSBPS-1073
```
[ ] Yes
[x] No
```
> DTSBPS-1073: Fix dependencies

- config/owasp/suppressions.xml
</suppress>
```
[ ] Yes
[x] No
```
> DTSBPS-1117: Suppress CVE 2022 42003

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSBPS-1236
```
[ ] Yes
[x] No
```
> DTSBPS-1236: Fix CVE 2022 31692
